### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by Scyks** [SimonJPegg/mvn_scalafmt#22]
Hey Guys,

i tried to use the plugin with Scala 2.12 and failed executing the task. Would it be possible to you to make the plugin work for 2.12 as well?

Would be very nice.

**Comment by jozic** [comment]
i have a build with scala 2.12.5 and mvn-scalafmt:0.7_1.5.1, it works fine

what's the failure you observe?

**Comment by Scyks** [comment]
I get the following error and I assume to have everything set up correctly
```
{
  "eqeqeq": true,
  "undef": true,
  "unused": "vars",
  "globals": {
    "_": true
  },
  "predef": [
    "sap",
    "app",
    "test",
    "module",
    "nv",
    "d3",
    "require",
    "process",
    "spyOnEvent",
    "spyOnProperty",
    "strictEqual",
    "opaTest",
    "ok",
    "deepEqual",
    "moment",
    "describe",
    "it",
    "expect",
    "__dirname",
    "exports",
    "_"
  ],

  "loopfunc": true,

  "browser": true,
  "devel": true,
  "jasmine": true,
  "jquery": true,
  "esversion": 6
}


ERROR] Failed to execute goal org.antipathy:mvn-scalafmt:0.7_1.5.1:format (default) on project insightsapp: Execution default of goal org.antipathy:mvn-scalafmt:0.7_1.5.1:format failed: An API incompatibility was encountered while executing org.antipathy:mvn-scalafmt:0.7_1.5.1:format: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.antipathy:mvn-scalafmt:0.7_1.5.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/unknown/.m2/repository/org/antipathy/mvn-scalafmt/0.7_1.5.1/mvn-scalafmt-0.7_1.5.1.jar
[ERROR] urls[1] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-core_2.12/1.5.1/scalafmt-core_2.12-1.5.1.jar
[ERROR] urls[2] = file:/Users/unknown/.m2/repository/org/scalameta/scalameta_2.12/1.7.0/scalameta_2.12-1.7.0.jar
[ERROR] urls[3] = file:/Users/unknown/.m2/repository/org/scalameta/common_2.12/1.7.0/common_2.12-1.7.0.jar
[ERROR] urls[4] = file:/Users/unknown/.m2/repository/com/lihaoyi/sourcecode_2.12/0.1.3/sourcecode_2.12-0.1.3.jar
[ERROR] urls[5] = file:/Users/unknown/.m2/repository/org/scalameta/dialects_2.12/1.7.0/dialects_2.12-1.7.0.jar
[ERROR] urls[6] = file:/Users/unknown/.m2/repository/org/scalameta/parsers_2.12/1.7.0/parsers_2.12-1.7.0.jar
[ERROR] urls[7] = file:/Users/unknown/.m2/repository/org/scalameta/tokens_2.12/1.7.0/tokens_2.12-1.7.0.jar
[ERROR] urls[8] = file:/Users/unknown/.m2/repository/org/scalameta/quasiquotes_2.12/1.7.0/quasiquotes_2.12-1.7.0.jar
[ERROR] urls[9] = file:/Users/unknown/.m2/repository/org/scalameta/tokenizers_2.12/1.7.0/tokenizers_2.12-1.7.0.jar
[ERROR] urls[10] = file:/Users/unknown/.m2/repository/com/lihaoyi/scalaparse_2.12/0.4.2/scalaparse_2.12-0.4.2.jar
[ERROR] urls[11] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse_2.12/0.4.2/fastparse_2.12-0.4.2.jar
[ERROR] urls[12] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse-utils_2.12/0.4.2/fastparse-utils_2.12-0.4.2.jar
[ERROR] urls[13] = file:/Users/unknown/.m2/repository/org/scalameta/transversers_2.12/1.7.0/transversers_2.12-1.7.0.jar
[ERROR] urls[14] = file:/Users/unknown/.m2/repository/org/scalameta/trees_2.12/1.7.0/trees_2.12-1.7.0.jar
[ERROR] urls[15] = file:/Users/unknown/.m2/repository/org/scalameta/inline_2.12/1.7.0/inline_2.12-1.7.0.jar
[ERROR] urls[16] = file:/Users/unknown/.m2/repository/org/scalameta/semantic_2.12/1.7.0/semantic_2.12-1.7.0.jar
[ERROR] urls[17] = file:/Users/unknown/.m2/repository/com/trueaccord/scalapb/scalapb-runtime_2.12/0.6.0-pre2/scalapb-runtime_2.12-0.6.0-pre2.jar
[ERROR] urls[18] = file:/Users/unknown/.m2/repository/com/trueaccord/lenses/lenses_2.12/0.4.10/lenses_2.12-0.4.10.jar
[ERROR] urls[19] = file:/Users/unknown/.m2/repository/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.jar
[ERROR] urls[20] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-core_2.12/0.4.0/metaconfig-core_2.12-0.4.0.jar
[ERROR] urls[21] = file:/Users/unknown/.m2/repository/org/scalameta/inputs_2.12/1.7.0/inputs_2.12-1.7.0.jar
[ERROR] urls[22] = file:/Users/unknown/.m2/repository/org/scalameta/io_2.12/1.7.0/io_2.12-1.7.0.jar
[ERROR] urls[23] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-typesafe-config_2.12/0.4.0/metaconfig-typesafe-config_2.12-0.4.0.jar
[ERROR] urls[24] = file:/Users/unknown/.m2/repository/com/typesafe/config/1.2.1/config-1.2.1.jar
[ERROR] urls[25] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-cli_2.12/1.5.1/scalafmt-cli_2.12-1.5.1.jar
[ERROR] urls[26] = file:/Users/unknown/.m2/repository/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.jar
[ERROR] urls[27] = file:/Users/unknown/.m2/repository/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.jar
[ERROR] urls[28] = file:/Users/unknown/.m2/repository/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar
[ERROR] urls[29] = file:/Users/unknown/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[30] = file:/Users/unknown/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[31] = file:/Users/unknown/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[32] = file:/Users/unknown/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[33] = file:/Users/unknown/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[34] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-core_2.11/1.3.0/scalafmt-core_2.11-1.3.0.jar
[ERROR] urls[35] = file:/Users/unknown/.m2/repository/org/scalameta/scalameta_2.11/1.7.0/scalameta_2.11-1.7.0.jar
[ERROR] urls[36] = file:/Users/unknown/.m2/repository/org/scalameta/common_2.11/1.7.0/common_2.11-1.7.0.jar
[ERROR] urls[37] = file:/Users/unknown/.m2/repository/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.jar
[ERROR] urls[38] = file:/Users/unknown/.m2/repository/org/scalameta/dialects_2.11/1.7.0/dialects_2.11-1.7.0.jar
[ERROR] urls[39] = file:/Users/unknown/.m2/repository/org/scalameta/parsers_2.11/1.7.0/parsers_2.11-1.7.0.jar
[ERROR] urls[40] = file:/Users/unknown/.m2/repository/org/scalameta/tokens_2.11/1.7.0/tokens_2.11-1.7.0.jar
[ERROR] urls[41] = file:/Users/unknown/.m2/repository/org/scalameta/quasiquotes_2.11/1.7.0/quasiquotes_2.11-1.7.0.jar
[ERROR] urls[42] = file:/Users/unknown/.m2/repository/org/scalameta/tokenizers_2.11/1.7.0/tokenizers_2.11-1.7.0.jar
[ERROR] urls[43] = file:/Users/unknown/.m2/repository/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.jar
[ERROR] urls[44] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse_2.11/0.4.2/fastparse_2.11-0.4.2.jar
[ERROR] urls[45] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse-utils_2.11/0.4.2/fastparse-utils_2.11-0.4.2.jar
[ERROR] urls[46] = file:/Users/unknown/.m2/repository/org/scalameta/transversers_2.11/1.7.0/transversers_2.11-1.7.0.jar
[ERROR] urls[47] = file:/Users/unknown/.m2/repository/org/scalameta/trees_2.11/1.7.0/trees_2.11-1.7.0.jar
[ERROR] urls[48] = file:/Users/unknown/.m2/repository/org/scalameta/inline_2.11/1.7.0/inline_2.11-1.7.0.jar
[ERROR] urls[49] = file:/Users/unknown/.m2/repository/org/scalameta/semantic_2.11/1.7.0/semantic_2.11-1.7.0.jar
[ERROR] urls[50] = file:/Users/unknown/.m2/repository/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.jar
[ERROR] urls[51] = file:/Users/unknown/.m2/repository/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.jar
[ERROR] urls[52] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-core_2.11/0.4.0/metaconfig-core_2.11-0.4.0.jar
[ERROR] urls[53] = file:/Users/unknown/.m2/repository/org/scalameta/inputs_2.11/1.7.0/inputs_2.11-1.7.0.jar
[ERROR] urls[54] = file:/Users/unknown/.m2/repository/org/scalameta/io_2.11/1.7.0/io_2.11-1.7.0.jar
[ERROR] urls[55] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-typesafe-config_2.11/0.4.0/metaconfig-typesafe-config_2.11-0.4.0.jar
[ERROR] urls[56] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-cli_2.11/1.3.0/scalafmt-cli_2.11-1.3.0.jar
[ERROR] urls[57] = file:/Users/unknown/.m2/repository/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar
[ERROR] urls[58] = file:/Users/unknown/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[59] = file:/Users/unknown/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.jar
[ERROR] urls[60] = file:/Users/unknown/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------

```

**Comment by Scyks** [comment]
I get the following error and I assume to have everything set up correctly
```
ERROR] Failed to execute goal org.antipathy:mvn-scalafmt:0.7_1.5.1:format (default) on project insightsapp: Execution default of goal org.antipathy:mvn-scalafmt:0.7_1.5.1:format failed: An API incompatibility was encountered while executing org.antipathy:mvn-scalafmt:0.7_1.5.1:format: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.antipathy:mvn-scalafmt:0.7_1.5.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/unknown/.m2/repository/org/antipathy/mvn-scalafmt/0.7_1.5.1/mvn-scalafmt-0.7_1.5.1.jar
[ERROR] urls[1] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-core_2.12/1.5.1/scalafmt-core_2.12-1.5.1.jar
[ERROR] urls[2] = file:/Users/unknown/.m2/repository/org/scalameta/scalameta_2.12/1.7.0/scalameta_2.12-1.7.0.jar
[ERROR] urls[3] = file:/Users/unknown/.m2/repository/org/scalameta/common_2.12/1.7.0/common_2.12-1.7.0.jar
[ERROR] urls[4] = file:/Users/unknown/.m2/repository/com/lihaoyi/sourcecode_2.12/0.1.3/sourcecode_2.12-0.1.3.jar
[ERROR] urls[5] = file:/Users/unknown/.m2/repository/org/scalameta/dialects_2.12/1.7.0/dialects_2.12-1.7.0.jar
[ERROR] urls[6] = file:/Users/unknown/.m2/repository/org/scalameta/parsers_2.12/1.7.0/parsers_2.12-1.7.0.jar
[ERROR] urls[7] = file:/Users/unknown/.m2/repository/org/scalameta/tokens_2.12/1.7.0/tokens_2.12-1.7.0.jar
[ERROR] urls[8] = file:/Users/unknown/.m2/repository/org/scalameta/quasiquotes_2.12/1.7.0/quasiquotes_2.12-1.7.0.jar
[ERROR] urls[9] = file:/Users/unknown/.m2/repository/org/scalameta/tokenizers_2.12/1.7.0/tokenizers_2.12-1.7.0.jar
[ERROR] urls[10] = file:/Users/unknown/.m2/repository/com/lihaoyi/scalaparse_2.12/0.4.2/scalaparse_2.12-0.4.2.jar
[ERROR] urls[11] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse_2.12/0.4.2/fastparse_2.12-0.4.2.jar
[ERROR] urls[12] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse-utils_2.12/0.4.2/fastparse-utils_2.12-0.4.2.jar
[ERROR] urls[13] = file:/Users/unknown/.m2/repository/org/scalameta/transversers_2.12/1.7.0/transversers_2.12-1.7.0.jar
[ERROR] urls[14] = file:/Users/unknown/.m2/repository/org/scalameta/trees_2.12/1.7.0/trees_2.12-1.7.0.jar
[ERROR] urls[15] = file:/Users/unknown/.m2/repository/org/scalameta/inline_2.12/1.7.0/inline_2.12-1.7.0.jar
[ERROR] urls[16] = file:/Users/unknown/.m2/repository/org/scalameta/semantic_2.12/1.7.0/semantic_2.12-1.7.0.jar
[ERROR] urls[17] = file:/Users/unknown/.m2/repository/com/trueaccord/scalapb/scalapb-runtime_2.12/0.6.0-pre2/scalapb-runtime_2.12-0.6.0-pre2.jar
[ERROR] urls[18] = file:/Users/unknown/.m2/repository/com/trueaccord/lenses/lenses_2.12/0.4.10/lenses_2.12-0.4.10.jar
[ERROR] urls[19] = file:/Users/unknown/.m2/repository/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.jar
[ERROR] urls[20] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-core_2.12/0.4.0/metaconfig-core_2.12-0.4.0.jar
[ERROR] urls[21] = file:/Users/unknown/.m2/repository/org/scalameta/inputs_2.12/1.7.0/inputs_2.12-1.7.0.jar
[ERROR] urls[22] = file:/Users/unknown/.m2/repository/org/scalameta/io_2.12/1.7.0/io_2.12-1.7.0.jar
[ERROR] urls[23] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-typesafe-config_2.12/0.4.0/metaconfig-typesafe-config_2.12-0.4.0.jar
[ERROR] urls[24] = file:/Users/unknown/.m2/repository/com/typesafe/config/1.2.1/config-1.2.1.jar
[ERROR] urls[25] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-cli_2.12/1.5.1/scalafmt-cli_2.12-1.5.1.jar
[ERROR] urls[26] = file:/Users/unknown/.m2/repository/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.jar
[ERROR] urls[27] = file:/Users/unknown/.m2/repository/com/github/scopt/scopt_2.12/3.5.0/scopt_2.12-3.5.0.jar
[ERROR] urls[28] = file:/Users/unknown/.m2/repository/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar
[ERROR] urls[29] = file:/Users/unknown/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[30] = file:/Users/unknown/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[31] = file:/Users/unknown/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[32] = file:/Users/unknown/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[33] = file:/Users/unknown/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[34] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-core_2.11/1.3.0/scalafmt-core_2.11-1.3.0.jar
[ERROR] urls[35] = file:/Users/unknown/.m2/repository/org/scalameta/scalameta_2.11/1.7.0/scalameta_2.11-1.7.0.jar
[ERROR] urls[36] = file:/Users/unknown/.m2/repository/org/scalameta/common_2.11/1.7.0/common_2.11-1.7.0.jar
[ERROR] urls[37] = file:/Users/unknown/.m2/repository/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.jar
[ERROR] urls[38] = file:/Users/unknown/.m2/repository/org/scalameta/dialects_2.11/1.7.0/dialects_2.11-1.7.0.jar
[ERROR] urls[39] = file:/Users/unknown/.m2/repository/org/scalameta/parsers_2.11/1.7.0/parsers_2.11-1.7.0.jar
[ERROR] urls[40] = file:/Users/unknown/.m2/repository/org/scalameta/tokens_2.11/1.7.0/tokens_2.11-1.7.0.jar
[ERROR] urls[41] = file:/Users/unknown/.m2/repository/org/scalameta/quasiquotes_2.11/1.7.0/quasiquotes_2.11-1.7.0.jar
[ERROR] urls[42] = file:/Users/unknown/.m2/repository/org/scalameta/tokenizers_2.11/1.7.0/tokenizers_2.11-1.7.0.jar
[ERROR] urls[43] = file:/Users/unknown/.m2/repository/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.jar
[ERROR] urls[44] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse_2.11/0.4.2/fastparse_2.11-0.4.2.jar
[ERROR] urls[45] = file:/Users/unknown/.m2/repository/com/lihaoyi/fastparse-utils_2.11/0.4.2/fastparse-utils_2.11-0.4.2.jar
[ERROR] urls[46] = file:/Users/unknown/.m2/repository/org/scalameta/transversers_2.11/1.7.0/transversers_2.11-1.7.0.jar
[ERROR] urls[47] = file:/Users/unknown/.m2/repository/org/scalameta/trees_2.11/1.7.0/trees_2.11-1.7.0.jar
[ERROR] urls[48] = file:/Users/unknown/.m2/repository/org/scalameta/inline_2.11/1.7.0/inline_2.11-1.7.0.jar
[ERROR] urls[49] = file:/Users/unknown/.m2/repository/org/scalameta/semantic_2.11/1.7.0/semantic_2.11-1.7.0.jar
[ERROR] urls[50] = file:/Users/unknown/.m2/repository/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.jar
[ERROR] urls[51] = file:/Users/unknown/.m2/repository/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.jar
[ERROR] urls[52] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-core_2.11/0.4.0/metaconfig-core_2.11-0.4.0.jar
[ERROR] urls[53] = file:/Users/unknown/.m2/repository/org/scalameta/inputs_2.11/1.7.0/inputs_2.11-1.7.0.jar
[ERROR] urls[54] = file:/Users/unknown/.m2/repository/org/scalameta/io_2.11/1.7.0/io_2.11-1.7.0.jar
[ERROR] urls[55] = file:/Users/unknown/.m2/repository/com/geirsson/metaconfig-typesafe-config_2.11/0.4.0/metaconfig-typesafe-config_2.11-0.4.0.jar
[ERROR] urls[56] = file:/Users/unknown/.m2/repository/com/geirsson/scalafmt-cli_2.11/1.3.0/scalafmt-cli_2.11-1.3.0.jar
[ERROR] urls[57] = file:/Users/unknown/.m2/repository/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar
[ERROR] urls[58] = file:/Users/unknown/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[59] = file:/Users/unknown/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.jar
[ERROR] urls[60] = file:/Users/unknown/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------

```

**Comment by Scyks** [comment]
Also by having a look at the pom file, there are dependencies for Scala 2.11 and therefore also scalameta 2.11 and scalafmt 2.11.

https://mvnrepository.com/artifact/org.antipathy/mvn-scalafmt/0.7_1.5.1

**Comment by SimonJPegg** [comment]
I'm not having any issues using this with scala 2.12.6 either.  But, I've pushed a version of `0.7_1.5.1` built on 2.12.6; The artefact is called `mvn_scalafmt_2.12` can you have a try and see if that works for you.  If so I'll have a look into cross building from now on.

**Comment by Scyks** [comment]
@SimonJPegg Seems like this works fine now, the error is gone and scalafmt works like a charm.
Thank you for providing the 2.12 version 👍

**Comment by SimonJPegg** [comment]
Scala version is now part of artefact id.  Closing this issue.
